# Generated by Django 3.2.16 on 2023-01-18 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_weather_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_app',
            name='currency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.currency'),
        ),
        migrations.AlterField(
            model_name='weather_app',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weather_app',
            name='weather',
            field=models.FloatField(),
        ),
    ]
