# Generated by Django 3.2.16 on 2023-01-19 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230118_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather_app',
            name='currency',
        ),
    ]
