# Generated by Django 3.2.16 on 2023-01-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_weather_app_currency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weather_App',
            new_name='WeatherApp',
        ),
    ]
