# Generated by Django 3.2.16 on 2023-01-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_weather_app_weatherapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherapp',
            name='weather',
            field=models.FloatField(default=0.0),
        ),
    ]
