# Generated by Django 3.2.16 on 2023-01-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_weatherapp_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=3)),
                ('weather', models.CharField(max_length=50)),
            ],
        ),
    ]
